### ISSUE TITLE
resnet50が動かない / resnet50 doesn't work

### ISSUE THREAD

**Issue by koji123** [fixstars/clpy#117]
コマンド
```
python -m clpy train_imagenet.py /opt/traindata/ILSVRC2012/train.ssv /opt/traindata/ILSVRC2012/val.ssv -g0 -a resnet50
```

エラー
```
/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/backends/cuda.py:85: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl).
  'cuDNN is not enabled.\n'
[JException in main training loop: clpy does not support this
Traceback (most recent call last):
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/koji.ueno/chainer/examples/imagenet/resnet50.py", line 97, in __call__
    h = self.bn1(self.conv1(x))
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/links/normalization/batch_normalization.py", line 144, in __call__
    running_var=self.avg_var, decay=decay)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py", line 530, in batch_normalization
    (x, gamma, beta))[0]
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py", line 107, in forward
    var = x.var(axis=self.axis)
  File "clpy/core/core.pyx", line 1083, in clpy.core.core.ndarray.var (clpy/core/core.cpp:20434)
  File "clpy/core/core.pyx", line 1092, in clpy.core.core.ndarray.var (clpy/core/core.cpp:20281)
  File "clpy/core/core.pyx", line 4185, in clpy.core.core._var (clpy/core/core.cpp:85782)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/clpy-2.1.0b0-py3.6-linux-x86_64.egg/clpy/__main__.py", line 8, in <module>
    exec(f.read())
  File "<string>", line 164, in <module>
  File "<string>", line 160, in main
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/koji.ueno/chainer/examples/imagenet/resnet50.py", line 97, in __call__
    h = self.bn1(self.conv1(x))
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/links/normalization/batch_normalization.py", line 144, in __call__
    running_var=self.avg_var, decay=decay)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py", line 530, in batch_normalization
    (x, gamma, beta))[0]
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/koji.ueno/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py", line 107, in forward
    var = x.var(axis=self.axis)
  File "clpy/core/core.pyx", line 1083, in clpy.core.core.ndarray.var (clpy/core/core.cpp:20434)
  File "clpy/core/core.pyx", line 1092, in clpy.core.core.ndarray.var (clpy/core/core.cpp:20281)
  File "clpy/core/core.pyx", line 4185, in clpy.core.core._var (clpy/core/core.cpp:85782)
NotImplementedError: clpy does not support this
```

**Comment by LWisteria** [comment]
@koji123 Thanks for reporting. I confirm this problem occurs.

@nsakabe-fixstars please fix (and add test if you can)
