### ISSUE TITLE
Word2vec cause Error at 1060 and Titan V

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#13]
# Word2vec cause Error at 1060 and Titan V
## Environment
* machine1(1060)
  * OS: CentOS 7.2.1511
  * CPU: Core i7-4790
  * MEM: 8GB
  * GPU: NVIDIA GeForce GTX 1060
  * SDK: CUDA 9.2
  * python: 3.6.4
  * clpy: b59da4c3
* machine2(titanv)
  * OS: Ubuntu 16.04.4 LTS
  * CPU: Core i9-7900X
  * MEM: 64GB
  * GPU: NVIDIA TITAN V
  * SDK: CUDA 9.2
  * python: 3.6.4
  * clpy: 28bcad2f

## Result
Two machine has almost same errors.
```
$ python train_word2vec.py -g 0
/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/backends/cuda.py:85: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl).
  'cuDNN is not enabled.\n'
GPU: 0
# unit: 100
Window: 5
Minibatch-size: 1000
# epoch: 20
Training model: skipgram
Output type: hsm

n_vocab: 10000
data length: 929589
Exception in main training loop: UNKNOWN ERROR
Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "train_word2vec.py", line 98, in __call__
    loss = self.loss_func(e, x)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/loss/hierarchical_softmax.py", line 364, in __call__
    return f(x, t, self.W)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function.py", line 342, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/loss/hierarchical_softmax.py", line 208, in forward_gpu
    wxy)
  File "clpy/core/elementwise.pxi", line 672, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/backend/function.pyx", line 149, in clpy.backend.function.Function.linear_launch
  File "clpy/backend/function.pyx", line 112, in clpy.backend.function._launch
  File "clpy/backend/opencl/utility.pyx", line 135, in clpy.backend.opencl.utility.RunNDRangeKernel
  File "clpy/backend/opencl/api.pyx", line 266, in clpy.backend.opencl.api.WaitForEvents
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train_word2vec.py", line 232, in <module>
    trainer.run()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/six.py", line 693, in reraise
    raise value
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "train_word2vec.py", line 98, in __call__
    loss = self.loss_func(e, x)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/loss/hierarchical_softmax.py", line 364, in __call__
    return f(x, t, self.W)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function.py", line 342, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/loss/hierarchical_softmax.py", line 208, in forward_gpu
    wxy)
  File "clpy/core/elementwise.pxi", line 672, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/backend/function.pyx", line 149, in clpy.backend.function.Function.linear_launch
  File "clpy/backend/function.pyx", line 112, in clpy.backend.function._launch
  File "clpy/backend/opencl/utility.pyx", line 135, in clpy.backend.opencl.utility.RunNDRangeKernel
  File "clpy/backend/opencl/api.pyx", line 266, in clpy.backend.opencl.api.WaitForEvents
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "clpy/backend/opencl/env.pyx", line 75, in clpy.backend.opencl.env.release
  File "clpy/backend/opencl/api.pyx", line 245, in clpy.backend.opencl.api.Flush
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR

```

**Comment by LWisteria** [comment]
@t-kitawaki Thanks for reporting
@nsakabe-fixstars Could you investigate this?

**Comment by ghost** [comment]
ok, i'll work on this.

**Comment by ghost** [comment]
I revealed the error code : `UNKNOWN ERROR: -9999`

**Comment by ghost** [comment]
According to https://streamhpc.com/blog/2013-04-28/opencl-error-codes/


-9999 | NVidia | clEnqueueNDRangeKernel | Illegal read or write to a buffer
-- | -- | -- | --

**Comment by ghost** [comment]
Generated CL kernel which causes buffer error here.
```
#include <clpy/carray.clh>

    typedef float T;

    __kernel void binary_hierarchical_softmax_forward
(
 __global float* const __restrict__ x,
 const CArray_2 x_info,
 __global float* const __restrict__ w,
 const CArray_2 w_info,
 __global int* const __restrict__ ts,
 const CArray_1 ts_info,
 __global int* const __restrict__ paths,
 const CArray_1 paths_info,
 __global float* const __restrict__ codes,
 const CArray_1 codes_info,
 __global int* const __restrict__ begins,
 const CArray_1 begins_info,
 int c,
 int max_length,
 __global float* const __restrict__ ls_data,
 const CArray_1 ls_info,
 __global float* const __restrict__ wxy_data,
 const CArray_1 wxy_info,
 CIndexer_1 _ind
 )
{
  set_CIndexer_1(&_ind, get_global_id(0));
  const size_t i = get_global_id(0); // TODO: Add offset and/or stride
  const size_t _ind_size = size_CIndexer_1(&_ind);
  T ls = ls_data[get_CArrayIndex_1(&ls_info, &_ind)];
  T wxy = wxy_data[get_CArrayIndex_1(&wxy_info, &_ind)];

    int ind = i / max_length;
    int offset = i - ind * max_length;
    int t = ts[get_CArrayIndexRaw_1(&ts_info, ind)];

    int begin = begins[get_CArrayIndexRaw_1(&begins_info, t)];
    int length = begins[get_CArrayIndexRaw_1(&begins_info, t + 1)] - begins[get_CArrayIndexRaw_1(&begins_info, t)];

    if (offset < length) {
      int p = begin + offset;
      int node = paths[get_CArrayIndexRaw_1(&paths_info, p)];

      T wx = 0;
      for (int j = 0; j < c; ++j) {
        int w_ind[] = {node, j};
        int x_ind[] = {ind, j};
        wx += w[get_CArrayIndexRaw_2(&w_info, w_ind)] * x[get_CArrayIndexRaw_2(&x_info, x_ind)];
      }
      wxy = wx * codes[get_CArrayIndexRaw_1(&codes_info, p)];
      ls = log(1 + exp(-wxy));
    } else {
      ls = 0;
    }

  ls_data[get_CArrayIndex_1(&ls_info, &_ind)] = ls;
  wxy_data[get_CArrayIndex_1(&wxy_info, &_ind)] = wxy;;
}
```

**Comment by ghost** [comment]
The reason of these errors was **mismatch of sizeof integer**.
I guess #12 is the same problem.

The macro [`get_CArrayIndexRaw_2`](https://github.com/fixstars/clpy/blob/clpy/clpy/core/include/clpy/carray.clh#L349) requires a `ptrdiff_t[]` argument.
The arguments passed actually are [w_ind, x_ind](https://github.com/chainer/chainer/blob/a01c33f515ec23d33eab6e2eff6aa5d4e99f414d/chainer/links/loss/hierarchical_softmax.py#L196), which is `int[]`.


The CL kernel code which passes `int[]` is a part of Chainer.

**Comment by ghost** [comment]
I updated the training time in the [wiki page](https://github.com/fixstars/clpy/wiki/chainer_example_performance_report#chainers-example-execution-timesec) with the version where this issue has been fixed.
