### ISSUE TITLE
opencl_tests/test_clblast.py raises CLBlastInvalidValue exception by af5fc6e

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#172]
As #171 reported, I got the same error on opencl_tests/test_clblast.py on https://github.com/fixstars/clpy/blob/af5fc6e6eb0e875a8b71c4aeb1dd4ae6806c048e/tests/clpy_tests/opencl_tests/test_clblast.py .
It' not raised on the last commit de78f5b0b157136b804117bf0fcffc1da2b00790 .

* Machine: NVIDIA GTX 1080 x2
* nvidia-docker run -t -t nvidia/cuda:latest

```
# apt install clinfo ocl-icd-opencl-dev
# mkdir -p /etc/OpenCL/vendors
# echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
# echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf
# echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf
$ cd /path/to/clpy
$ python setup.py install
$ cd tests/clpy_tests/opencl_tests
$ python -m pytest test_clblast.py
================================================================================================= test session starts =================================================================================================
platform linux -- Python 3.6.5, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/yoshifuji/repo/clpy, inifile: setup.cfg
collected 22 items

test_clblast.py FFFFFFFFFException ignored in: <bound method PooledMemory.free of <clpy.backend.memory.PooledMemory object at 0x7fd96fd811d0>>
Traceback (most recent call last):
  File "clpy/backend/memory.pyx", line 533, in clpy.backend.memory.PooledMemory.free
  File "clpy/backend/memory.pyx", line 759, in clpy.backend.memory.SingleDeviceMemoryPool.free
  File "clpy/backend/memory.pyx", line 770, in clpy.backend.memory.SingleDeviceMemoryPool.free
RuntimeError: Cannot free out-of-pool memory
FFF..FFFFFFFF                                                                                                                                                                          [100%]

====================================================================================================== FAILURES =======================================================================================================
_______________________________________________________________________________________ TestBlas3GEMM.test_alpha_matrix_matrix ________________________________________________________________________________________

self = <test_clblast.TestBlas3GEMM testMethod=test_alpha_matrix_matrix>, dtype = <class 'numpy.float32'>, blasfunc = <built-in function sgemm>

    @for_each_dtype_and_blasfunc_pair(GEMM_pairs)
    def test_alpha_matrix_matrix(self, dtype, blasfunc):
        npA = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                          dtype=dtype)  # row-major
        npB = numpy.array([[10, 11, 12], [13, 14, 15], [
                          16, 17, 18]], dtype=dtype)  # row-major
        transa = 0  # A is not transposed in c-style(row-major)
        transb = 0  # B is not transposed in c-style(row-major)
        alpha = 2.0
        beta = 0.0

        m = npA.shape[0]
        n = npB.shape[1]
        k = npA.shape[1]

        clpA = clpy.ndarray(npA.shape, dtype=dtype)  # col major in clpy
        clpA.set(npA)
        clpB = clpy.ndarray(npB.shape, dtype=dtype)  # col major in clpy
        clpB.set(npB)

        expectedC = numpy.dot(npA, npB) * alpha
        clpC = clpy.ndarray(expectedC.shape, dtype=dtype)

        clpA, transa, lda = core._mat_to_cublas_contiguous(
            clpA, transa)  # as cublas-style
        clpB, transb, ldb = core._mat_to_cublas_contiguous(
            clpB, transb)  # as cublas-style
        ldc = clpC.shape[1]

        # alpha * (A^t x B^T) in col-major = alpha * AxB in row major
        blasfunc('C', transa, transb,
                 m, n, k, alpha,
                 clpA, lda,
                 clpB, ldb,
>                beta, clpC, ldc
                 )

test_clblast.py:613:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
clpy/backend/opencl/clblast/clblast.pyx:95: in clpy.backend.opencl.clblast.clblast.sgemm
    ???
clpy/backend/opencl/clblast/clblast.pyx:109: in clpy.backend.opencl.clblast.clblast.sgemm
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   clpy.backend.opencl.clblast.clblast.CLBlastRuntimeError: CLBlastInvalidValue

clpy/backend/opencl/clblast/clblast.pyx:92: CLBlastRuntimeError
------------------------------------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------------------------------------
dtype: float32 , blasfunc: <built-in function sgemm>
------------------------------------------------------------------------------------------------ Captured stderr call -------------------------------------------------------------------------------------------------
CLBlast: OpenCL error: clGetProgramInfo: -30

[snip]
```

**Comment by LWisteria** [comment]
And as I reported on #171, this error does not occour on a single device machine and multiple AMD Radeon machine. It might be only on multiple NVIDIA devices.

**Comment by LWisteria** [comment]
Simple one

```
$ python test_clblast.py TestBlas3GEMM.test_alpha_matrix_matrix
CLBlast: OpenCL error: clGetProgramInfo: -30
dtype: float32 , blasfunc: <built-in function sgemm>
E
======================================================================
ERROR: test_alpha_matrix_matrix (__main__.TestBlas3GEMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_clblast.py", line 20, in test_func
    impl(self, *args, **kwargs)
  File "test_clblast.py", line 613, in test_alpha_matrix_matrix
    beta, clpC, ldc
  File "clpy/backend/opencl/clblast/clblast.pyx", line 95, in clpy.backend.opencl.clblast.clblast.sgemm
  File "clpy/backend/opencl/clblast/clblast.pyx", line 109, in clpy.backend.opencl.clblast.clblast.sgemm
  File "clpy/backend/opencl/clblast/clblast.pyx", line 92, in clpy.backend.opencl.clblast.clblast.clblast_sgemm
clpy.backend.opencl.clblast.clblast.CLBlastRuntimeError: CLBlastInvalidValue

----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (errors=1)
```

**Comment by LWisteria** [comment]
The error was removed when https://github.com/fixstars/clpy/commit/af5fc6e6eb0e875a8b71c4aeb1dd4ae6806c048e#diff-2dd2534937b0e0a39ec2b84ffce0c6cfL103 was reverted

num_devices must be 1...?

**Comment by LWisteria** [comment]
[`CLBlastInvalidValue` means `CL_INVALID_VALUE`](https://github.com/CNugteren/CLBlast/blob/1.4.1/include/clblast_c.h#L55)

**Comment by LWisteria** [comment]
#175 resolved this.
