### ISSUE TITLE
OpenCLがインストールできていなかった / Chainerのバージョン違い / エイリアス指定忘れ / Intel GPUなどfp16サポートしていないデバイス

### ISSUE THREAD

**Issue by usasho** [fixstars/clpy#239]
こんばんは　前回も何回か質問したのですが
なかなかここから先に行けていません

ログ残しておきます　よろしくおねがいします

Log
python3 -m clpy train.py -e 10 -b 1 -g 0
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/__init__.py", line 17, in <module>
    from clpy import core  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/__init__.py", line 1, in <module>
    from clpy.core import core  # NOQA
  File "clpy/backend/device.pxd", line 4, in init clpy.core.core
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/backend/__init__.py", line 4, in <module>
    from clpy.backend import device  # NOQA
  File "clpy/backend/device.pyx", line 1, in init clpy.backend.device
  File "clpy/backend/opencl/env.pyx", line 81, in init clpy.backend.opencl.env
  File "clpy/backend/opencl/api.pyx", line 16, in clpy.backend.opencl.api.GetPlatformIDs
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -1001 
root@scss-OptiPlex-7010:~/pc/sep# python3 -m clpy
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/__init__.py", line 17, in <module>
    from clpy import core  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/__init__.py", line 1, in <module>
    from clpy.core import core  # NOQA
  File "clpy/backend/device.pxd", line 4, in init clpy.core.core
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/backend/__init__.py", line 4, in <module>
    from clpy.backend import device  # NOQA
  File "clpy/backend/device.pyx", line 1, in init clpy.backend.device
  File "clpy/backend/opencl/env.pyx", line 81, in init clpy.backend.opencl.env
  File "clpy/backend/opencl/api.pyx", line 16, in clpy.backend.opencl.api.GetPlatformIDs
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -1001

**Comment by LWisteria** [comment]
ログの一番最後に出ている通り`clGetPlatformIDs()`が動いていないようです。これはつまり、OpenCL環境が動作していない可能性が高いのですが、確認されましたでしょうか？例えば`clinfo`の結果を教えてください。

また、その他、OSやCPU/GPU等の計算機情報も合わせて教えていただければ、もう少し有意義な回答ができると思います。

**Comment by usasho** [comment]
確かにランタイムエラーでした
現在エラーはないのですが

Cupyを導入してくださいというエラーが
どう処理すればよろしいですかねTraceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/__main__.py", line 8, in <module>
    exec(f.read())
  File "<string>", line 202, in <module>
  File "<string>", line 149, in main
  File "/usr/local/lib/python3.7/dist-packages/chainer/backends/cuda.py", line 163, in get_device_from_id
    check_cuda_available()
  File "/usr/local/lib/python3.7/dist-packages/chainer/backends/cuda.py", line 93, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupyx'

**Comment by ghost** [comment]
> RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupyx'

から察するに Chainer のバージョンが違うのではないでしょうか。  
現行の clpy は cupy v2.1.0 をベースとしていて [Chainer v3.3.0 で確認しております。](https://github.com/fixstars/clpy#compatibility-with-chainer)

**Comment by usasho** [comment]
回答ありがとうございます。
chainer のバージョンは3.3.0です。
もしかしたら重複インストールもあるので 一度アインストールしてみます

**Comment by usasho** [comment]
再インストールしましたが　このようになってます
やはりCuda　モジュールがないですね


Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/__main__.py", line 8, in <module>
    exec(f.read())
  File "<string>", line 201, in <module>
  File "<string>", line 148, in main
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/backends/cuda.py", line 158, in get_device_from_id
    check_cuda_available()
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/backends/cuda.py", line 80, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupy'

**Comment by LWisteria** [comment]
cupyが見つからないのであれば、cupyエイリアスが効いていないのだと思います。
READMEをお読みになり、cupyエイリアスでclpyが呼べるようにして実行してみてください。

あと、先述の通り、実行環境や、あるいはコマンドおよびスクリプトなど詳細を教えていただけると、早く的確な回答できるかと存じます。

**Comment by usasho** [comment]
エイリアスを0に設定したところエラーは出なくなりましたが
実行エラーが起きてます・・・

環境は　Core I3  3220 
RAM 4GB HDD 500GB
Linux Ubuntu 18.10 
Desktop PC OptoPlex 7010
root@scss-OptiPlex-7010:~/pc/sep# clinfo
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 1.2 LINUX
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_fp64 
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel(R) OpenCL
Number of devices                                 1
  Device Name                                             Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 (Build 8)
  Driver Version                                  1.2.0.8
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               4
  Max clock frequency                             3300MHz
  Device Partition                                (core)
    Max number of sub-devices                     4
    Supported partition types                     by counts, equally, by names (Intel)
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             8192x8192x8192
  Max work group size                             8192
  Preferred work group size multiple              128
  Preferred / native vector sizes                 
    char                                                 1 / 16      
    short                                                1 / 8       
    int                                                  1 / 4       
    long                                                 1 / 2       
    half                                                 0 / 0        (n/a)
    float                                                1 / 8       
    double                                               1 / 4        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              4015206400 (3.739GiB)
  Error Correction support                        No
  Max memory allocation                           1003801600 (957.3MiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        262144 (256KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             480
    Max size for 1D images from buffer            62737600 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 480
    Max number of write image args                480
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max number of constant args                     480
  Max constant buffer size                        131072 (128KiB)
  Max size of kernel argument                     3840 (3.75KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Local thread execution (Intel)                Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_fp64 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel(R) OpenCL
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [INTEL]
  clCreateContext(NULL, ...) [default]            Success [INTEL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Intel(R) OpenCL
    Device Name                                           Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Intel(R) OpenCL
    Device Name                                           Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel(R) OpenCL
    Device Name                                           Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1

どうでしょうか・・・

**Comment by usasho** [comment]
実行エラーのログです

root@scss-OptiPlex-7010:~/pc/sep# python3 -m clpy  train.py -e 10 -b 1 -g0
GPU: 0
# Minibatch-size: 1
# patch-length: 512
# epoch: 10
# result directory:  result
# subepoch  4
# number of patterns 4
/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/backends/cuda.py:85: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl).
  'cuDNN is not enabled.\n'
# load unet.model
Exception in main training loop: CL_BUILD_PROGRAM_FAILURE Device#0: Compilation started
In file included from 1:2:
/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/carray.clh:2:26: error: OpenCL extension 'cl_khr_fp16' is unsupported
In file included from 1:2:
In file included from /usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/carray.clh:535:
/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/fp16.clh:35:10: error: dereferencing of half pointers is illegal in OpenCL. Use vload_half function instead
In file included from 1:2:
/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/carray.clh:581:10: error: dereferencing of half pointers is illegal in OpenCL. Use vload_half function instead
Compilation failed

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "<string>", line 103, in __call__
  File "<string>", line 78, in __call__
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/links/connection/convolution_2d.py", line 156, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/functions/connection/convolution_2d.py", line 467, in convolution_2d
    y, = fnode.apply(args)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/functions/connection/convolution_2d.py", line 198, in forward_gpu
    cover_all=self.cover_all)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/utils/conv.py", line 121, in im2col_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, dy, dx, col)
  File "clpy/core/elementwise.pxi", line 628, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 39, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 479, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 15, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 44, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 192, in clpy.core.core.compile_with_cache
  File "clpy/backend/opencl/utility.pyx", line 132, in clpy.backend.opencl.utility.CreateProgram
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "clpy/backend/opencl/utility.pyx", line 122, in clpy.backend.opencl.utility.CreateProgram
  File "clpy/backend/opencl/api.pyx", line 157, in clpy.backend.opencl.api.BuildProgram
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: CL_BUILD_PROGRAM_FAILURE 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/__main__.py", line 8, in <module>
    exec(f.read())
  File "<string>", line 201, in <module>
  File "<string>", line 197, in main
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "<string>", line 103, in __call__
  File "<string>", line 78, in __call__
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/links/connection/convolution_2d.py", line 156, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/functions/connection/convolution_2d.py", line 467, in convolution_2d
    y, = fnode.apply(args)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/functions/connection/convolution_2d.py", line 198, in forward_gpu
    cover_all=self.cover_all)
  File "/usr/local/lib/python3.7/dist-packages/chainer-3.3.0-py3.7.egg/chainer/utils/conv.py", line 121, in im2col_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, dy, dx, col)
  File "clpy/core/elementwise.pxi", line 628, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 39, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 479, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 15, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 44, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 192, in clpy.core.core.compile_with_cache
  File "clpy/backend/opencl/utility.pyx", line 132, in clpy.backend.opencl.utility.CreateProgram
clpy.backend.opencl.exceptions.OpenCLProgramBuildError: CL_BUILD_PROGRAM_FAILURE Device#0: Compilation started
In file included from 1:2:
/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/carray.clh:2:26: error: OpenCL extension 'cl_khr_fp16' is unsupported
In file included from 1:2:
In file included from /usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/carray.clh:535:
/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/fp16.clh:35:10: error: dereferencing of half pointers is illegal in OpenCL. Use vload_half function instead
In file included from 1:2:
/usr/local/lib/python3.7/dist-packages/clpy-2.1.0rc1-py3.7-linux-x86_64.egg/clpy/core/include/clpy/carray.clh:581:10: error: dereferencing of half pointers is illegal in OpenCL. Use vload_half function instead
Compilation failed

**Comment by LWisteria** [comment]
エラーメッセージを読んでもらうと分かる通り

> error: OpenCL extension 'cl_khr_fp16' is unsupported

とのことです。お使いのデバイスでは対応していないようです。

**Comment by vorj** [comment]
@usasho [`224-check-cl_khr_fp16-support`](https://github.com/fixstars/clpy/tree/224-check-cl_khr_fp16-support)ブランチをチェックアウトしてインストールしてみてもらえますか？このブランチのclpyであれば `cl_khr_fp16` に対応していないデバイスでも動くはずです．

**Comment by LWisteria** [comment]
note: 該当ブランチは #225 の開発中。fp16サポートしていない場合に単体試験が通らないが、fp16に関係ない機能は実行可能。

**Comment by usasho** [comment]
やってみます

**Comment by LWisteria** [comment]
長期間応答がないので閉じます。必要があればまた報告をお願いします。
