### ISSUE TITLE
Update chainer example performance report

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#41]
We should update https://github.com/fixstars/clpy/wiki/chainer_example_performance_report

Update: we need all chainer's performance report.

**Comment by LWisteria** [comment]
@t-kitawaki take this please

**Comment by ghost** [comment]
ok. I take it.

**Comment by ghost** [comment]
cannot run ImageNet example due to error at vega.
```
/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/backends/cuda.py:85: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl).
  'cuDNN is not enabled.\n'
Exception in main training loop: CL_BUILD_PROGRAM_FAILURE /tmp/OCL26842T35.cl:568:19: error: implicit declaration of function 'get_CArrayIndexRaw_4' is invalid in C99
        col = img[get_CArrayIndexRaw_4(&img_info, in_x + w * (in_y + h * c0))];
                  ^
1 error generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/kitawaki/clpy-chainer/chainer/examples/imagenet/nin.py", line 28, in __call__
    h = F.max_pooling_2d(F.relu(self.mlpconv1(x)), 3, stride=2)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/mlp_convolution_2d.py", line 99, in __call__
    x = f(l(x))
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/convolution_2d.py", line 156, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 467, in convolution_2d
    y, = fnode.apply(args)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 198, in forward_gpu
    cover_all=self.cover_all)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/utils/conv.py", line 121, in im2col_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, dy, dx, col)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 182, in clpy.core.core.compile_with_cache
  File "clpy/backend/opencl/utility.pyx", line 89, in clpy.backend.opencl.utility.CreateProgram
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "clpy/backend/opencl/utility.pyx", line 83, in clpy.backend.opencl.utility.CreateProgram
  File "clpy/backend/opencl/api.pyx", line 112, in clpy.backend.opencl.api.BuildProgram
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: CL_BUILD_PROGRAM_FAILURE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/clpy-2.1.0a0-py3.6-linux-x86_64.egg/clpy/__main__.py", line 8, in <module>
    exec(f.read())
  File "<string>", line 164, in <module>
  File "<string>", line 160, in main
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/six.py", line 693, in reraise
    raise value
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/kitawaki/clpy-chainer/chainer/examples/imagenet/nin.py", line 28, in __call__
    h = F.max_pooling_2d(F.relu(self.mlpconv1(x)), 3, stride=2)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/mlp_convolution_2d.py", line 99, in __call__
    x = f(l(x))
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/convolution_2d.py", line 156, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 467, in convolution_2d
    y, = fnode.apply(args)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 198, in forward_gpu
    cover_all=self.cover_all)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/utils/conv.py", line 121, in im2col_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, dy, dx, col)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 182, in clpy.core.core.compile_with_cache
  File "clpy/backend/opencl/utility.pyx", line 89, in clpy.backend.opencl.utility.CreateProgram
clpy.backend.opencl.exceptions.OpenCLProgramBuildError: CL_BUILD_PROGRAM_FAILURE /tmp/OCL26842T35.cl:568:19: error: implicit declaration of function 'get_CArrayIndexRaw_4' is invalid in C99
        col = img[get_CArrayIndexRaw_4(&img_info, in_x + w * (in_y + h * c0))];
                  ^
1 error generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR
```

**Comment by LWisteria** [comment]
oh...

@vorj do you have any ideas?

**Comment by ghost** [comment]
cannot run ImageNet example due to error at titanv too.
```

/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/backends/cuda.py:85: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl).
  'cuDNN is not enabled.\n'
Exception in main training loop: UNKNOWN ERROR: -9999
Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/kitawaki/clpy-chainer/chainer/examples/imagenet/nin.py", line 28, in __call__
    h = F.max_pooling_2d(F.relu(self.mlpconv1(x)), 3, stride=2)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/mlp_convolution_2d.py", line 99, in __call__
    x = f(l(x))
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/convolution_2d.py", line 156, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 467, in convolution_2d
    y, = fnode.apply(args)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 198, in forward_gpu
    cover_all=self.cover_all)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/utils/conv.py", line 121, in im2col_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, dy, dx, col)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 182, in clpy.core.core.compile_with_cache
  File "clpy/backend/opencl/utility.pyx", line 89, in clpy.backend.opencl.utility.CreateProgram
  File "clpy/backend/opencl/utility.pyx", line 83, in clpy.backend.opencl.utility.CreateProgram
  File "clpy/backend/opencl/api.pyx", line 112, in clpy.backend.opencl.api.BuildProgram
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/clpy-2.1.0a0-py3.6-linux-x86_64.egg/clpy/__main__.py", line 8, in <module>
    exec(f.read())
  File "<string>", line 164, in <module>
  File "<string>", line 160, in main
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/six.py", line 693, in reraise
    raise value
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/home/kitawaki/clpy-chainer/chainer/examples/imagenet/nin.py", line 28, in __call__
    h = F.max_pooling_2d(F.relu(self.mlpconv1(x)), 3, stride=2)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/mlp_convolution_2d.py", line 99, in __call__
    x = f(l(x))
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/links/connection/convolution_2d.py", line 156, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 467, in convolution_2d
    y, = fnode.apply(args)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/connection/convolution_2d.py", line 198, in forward_gpu
    cover_all=self.cover_all)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/utils/conv.py", line 121, in im2col_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, dy, dx, col)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 182, in clpy.core.core.compile_with_cache
  File "clpy/backend/opencl/utility.pyx", line 89, in clpy.backend.opencl.utility.CreateProgram
  File "clpy/backend/opencl/utility.pyx", line 83, in clpy.backend.opencl.utility.CreateProgram
  File "clpy/backend/opencl/api.pyx", line 112, in clpy.backend.opencl.api.BuildProgram
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -9999

```

**Comment by LWisteria** [comment]
I confirmed this problem.

@t-kitawaki Please make a issue and report this problem.

**Comment by ghost** [comment]
@LWisteria I made issue and report this.

**Comment by LWisteria** [comment]
@t-kitawaki Thank you. Continue this work after resolve #47.

**Comment by ghost** [comment]
update machine specs
- Primary machine (furyx)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i7-4790
    - MEM: 16GB
    - GPU: AMD Radeon R9 Fury X
    - SDK: amdgpu-pro-17.50-511655
- New Primary machine (vega)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i7-7700
    - MEM: 8GB
    - GPU: AMD Radeon Vega Frontier Edition (Air Cooled)
    - SDK: amdgpu-pro-18.20-621984
- Secondary machine (gf1060)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i7-4790
    - MEM: 8GB
    - GPU: NVIDIA GeForce GTX 1060
    - SDK: CUDA 9.2
- New Secondary machine (titanv)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i9-7900X
    - MEM: 64GB
    - GPU: NVIDIA TITAN V
    - SDK: CUDA 9.2

**Comment by LWisteria** [comment]
@t-kitawaki Now we call vega and titanv just "primary" and "secondary" (see README). Therefore, furyx and gf1060 should be called "old" primary/secondary.

**Comment by ghost** [comment]
ok. 
- Primary machine (vega)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i7-7700
    - MEM: 8GB
    - GPU: AMD Radeon Vega Frontier Edition (Air Cooled)
    - SDK: amdgpu-pro-18.20-621984
- Old Primary machine (furyx)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i7-4790
    - MEM: 16GB
    - GPU: AMD Radeon R9 Fury X
    - SDK: amdgpu-pro-17.50-511655
- Secondary machine (titanv)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i9-7900X
    - MEM: 64GB
    - GPU: NVIDIA TITAN V
    - SDK: CUDA 9.2
- Old Secondary machine (gf1060)
    - OS: Ubuntu 16.04.5 LTS
    - CPU: Core i7-4790
    - MEM: 8GB
    - GPU: NVIDIA GeForce GTX 1060
    - SDK: CUDA 9.2

**Comment by ghost** [comment]
Example settings
- ImageNet
    - src: chainer/examples/imagenet/train_imagenet.py
    - change: Change train_imagenet.py as below to get elapsed_time.
    - cmd: python train_imagenet.py /path/to/traindata/train.ssv /path/to/traindata/val.ssv -B10 -E1 -g0
    - execution time: See elapsed_time at iteration 2000.

```
diff --git a/examples/imagenet/train_imagenet.py b/examples/imagenet/train_imagenet.py
index e2babed..168c710 100755
--- a/examples/imagenet/train_imagenet.py
+++ b/examples/imagenet/train_imagenet.py
@@ -150,7 +150,7 @@ def main():
     trainer.extend(extensions.observe_lr(), trigger=log_interval)
     trainer.extend(extensions.PrintReport([
         'epoch', 'iteration', 'main/loss', 'validation/main/loss',
-        'main/accuracy', 'validation/main/accuracy', 'lr'
+        'main/accuracy', 'validation/main/accuracy', 'lr', 'elapsed_time'
     ]), trigger=log_interval)
     trainer.extend(extensions.ProgressBar(update_interval=10))
```

**Comment by ghost** [comment]
- [ ] vega : 
- [ ] titanv : 
- [x] titanv(cuda) : 215.747
- [ ] furyx : 
- [ ] gf1060 : 
- [ ] gf1060(cuda) :

**Comment by LWisteria** [comment]
@nsakabe-fixstars please continue this issue after #47

**Comment by ghost** [comment]
* titanv: 153.185

**Comment by ghost** [comment]
* vega: 690.28

**Comment by ghost** [comment]
* furyx: 581.927

**Comment by ghost** [comment]
* gf1060: 407.442

**Comment by ghost** [comment]
* gf1060(cuda9.2, cuDNN 7.1, Chainer 3.3.0, CuPy 2.1.0): 129.613

**Comment by ghost** [comment]
* titanv(cuda 9.2, cuDNN 7.1, Chainer 3.3.0, CuPy 2.1.0): 118.442

**Comment by LWisteria** [comment]
@nsakabe-fixstars I updated this issue's goal. Please update all example's

**Comment by ghost** [comment]
@LWisteria OK. I'm working on performance tests.

**Comment by ghost** [comment]
These examples' execution times have been measured.

| machine       | gpu          | mnist    | ptb         | word2vec  | ImageNet   |
| ------------  | ----------   | -------- | ----------- | --------- | ---------- |
| primary       | vega         | 109.745  | 1157.57     | 499.036   | 690.28     |
| old primary   | furyx        | 128.843  | 896.225     | 609.921   | 581.927    |
| secondary     | titanv(clpy) | 79.8286  | 381.014     | 194.613   | 153.185    |
| secondary     | titanv(cupy) | 38.4101  | 165.07      | 28.212    | 118.442    |
| old secondary | gf1060(clpy) | 97.0151  | 537.912     | 131.664   | 407.442    |
| old secondary | gf1060(cupy) | 41.4302  | 200.497     | 42.4418   | 129.613    |

**Comment by ghost** [comment]
Also, new `chainer_example_performance_report.md` for updating wiki is ready.

**Comment by LWisteria** [comment]
@nsakabe-fixstars please update wiki page!

**Comment by ghost** [comment]
Done! https://github.com/fixstars/clpy/wiki/chainer_example_performance_report/_compare/b9048f58a8a54fe232ab7d499e0f1d1e8e703c02...062754b645606cf279a55abf0bf1fa605026f8c2

**Comment by LWisteria** [comment]
@nsakabe-fixstars thanks!
