### ISSUE TITLE
"RuntimeError: Build ultima is failed." occured

### ISSUE THREAD

**Issue by telmin** [fixstars/clpy#42]
d053ee1904880f86b4ea0cbd5146431fded9b029 をビルドしようとした際、Ultimaのビルドで以下のエラーが発生します。

```
$ python setup.py install
building ultima
/tmp/ultima-bfe7ed.o: In function `main':
ultima.cpp:(.text+0x8a9): undefined reference to `clang::tooling::ClangTool::ClangTool(clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::shared_ptr<clang::PCHContainerOperations>)'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::VisitFriendDecl(clang::FriendDecl*)':
ultima.cpp:(.text._ZN6ultima12decl_visitor15VisitFriendDeclEPN5clang10FriendDeclE[_ZN6ultima12decl_visitor15VisitFriendDeclEPN5clang10FriendDeclE]+0x195): undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::VisitCXXRecordDecl(clang::CXXRecordDecl*, bool)':
ultima.cpp:(.text._ZN6ultima12decl_visitor18VisitCXXRecordDeclEPN5clang13CXXRecordDeclEb[_ZN6ultima12decl_visitor18VisitCXXRecordDeclEPN5clang13CXXRecordDeclEb]+0x461): undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::VisitTypeAliasDecl(clang::TypeAliasDecl*)':
ultima.cpp:(.text._ZN6ultima12decl_visitor18VisitTypeAliasDeclEPN5clang13TypeAliasDeclE[_ZN6ultima12decl_visitor18VisitTypeAliasDeclEPN5clang13TypeAliasDeclE]+0x1e8): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::VisitFunctionDecl(clang::FunctionDecl*)':
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x1cf): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x1ff): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x583): undefined reference to `clang::DeclarationNameInfo::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0xc14): undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0xd52): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0xde4): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x136f): undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x17bc): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x185f): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x189e): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x1941): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x1df8): undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x214b): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x23a5): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x2441): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE[_ZN6ultima12decl_visitor17VisitFunctionDeclEPN5clang12FunctionDeclE]+0x255b): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::VisitVarDecl(clang::VarDecl*, bool)':
ultima.cpp:(.text._ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb[_ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb]+0x136a): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb[_ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb]+0x13ac): undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb[_ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb]+0x157f): undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb[_ZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEb]+0x16c9): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::stmt_visitor::VisitBlockExpr(clang::BlockExpr*)':
ultima.cpp:(.text._ZN6ultima12stmt_visitor14VisitBlockExprEPN5clang9BlockExprE[_ZN6ultima12stmt_visitor14VisitBlockExprEPN5clang9BlockExprE]+0x166): undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::stmt_visitor::VisitCXXMemberCallExpr(clang::CXXMemberCallExpr*)':
ultima.cpp:(.text._ZN6ultima12stmt_visitor22VisitCXXMemberCallExprEPN5clang17CXXMemberCallExprE[_ZN6ultima12stmt_visitor22VisitCXXMemberCallExprEPN5clang17CXXMemberCallExprE]+0x112): undefined reference to `clang::DeclarationNameInfo::getAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::stmt_visitor::VisitCXXOperatorCallExpr(clang::CXXOperatorCallExpr*)':
ultima.cpp:(.text._ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE[_ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE]+0x225): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE[_ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE]+0x8ba): undefined reference to `clang::DeclarationNameInfo::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE[_ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE]+0xb0c): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE[_ZN6ultima12stmt_visitor24VisitCXXOperatorCallExprEPN5clang19CXXOperatorCallExprE]+0xb75): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::stmt_visitor::VisitUserDefinedLiteral(clang::UserDefinedLiteral*)':
ultima.cpp:(.text._ZN6ultima12stmt_visitor23VisitUserDefinedLiteralEPN5clang18UserDefinedLiteralE[_ZN6ultima12stmt_visitor23VisitUserDefinedLiteralEPN5clang18UserDefinedLiteralE]+0x443): undefined reference to `llvm::APInt::toString[abi:cxx11](unsigned int, bool) const'
/tmp/ultima-bfe7ed.o: In function `ultima::stmt_visitor::VisitLambdaExpr(clang::LambdaExpr*)':
ultima.cpp:(.text._ZN6ultima12stmt_visitor15VisitLambdaExprEPN5clang10LambdaExprE[_ZN6ultima12stmt_visitor15VisitLambdaExprEPN5clang10LambdaExprE]+0x48a): undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::stmt_visitor::print_template_argument(clang::TemplateArgument const&)':
ultima.cpp:(.text._ZN6ultima12stmt_visitor23print_template_argumentERKN5clang16TemplateArgumentE[_ZN6ultima12stmt_visitor23print_template_argumentERKN5clang16TemplateArgumentE]+0x39): undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::printTemplateParameters(clang::TemplateParameterList const*)':
ultima.cpp:(.text._ZN6ultima12decl_visitor23printTemplateParametersEPKN5clang21TemplateParameterListE[_ZN6ultima12decl_visitor23printTemplateParametersEPKN5clang21TemplateParameterListE]+0x313): undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::VisitDeclContext(clang::DeclContext*, bool)':
ultima.cpp:(.text._ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb[_ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb]+0x5ca): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb[_ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb]+0x601): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb[_ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb]+0x6ba): undefined reference to `clang::QualType::getAsString[abi:cxx11]() const'
ultima.cpp:(.text._ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb[_ZN6ultima12decl_visitor16VisitDeclContextEPN5clang11DeclContextEb]+0x6f1): undefined reference to `clang::NamedDecl::getQualifiedNameAsString[abi:cxx11]() const'
/tmp/ultima-bfe7ed.o: In function `ultima::decl_visitor::VisitVarDecl(clang::VarDecl*, bool)::{lambda(clang::TemplateSpecializationType const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)#1}::operator()(clang::TemplateSpecializationType const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool) const':
ultima.cpp:(.text._ZZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEbENKUlPKNS1_26TemplateSpecializationTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbbE_clES6_SE_bb[_ZZN6ultima12decl_visitor12VisitVarDeclEPN5clang7VarDeclEbENKUlPKNS1_26TemplateSpecializationTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbbE_clES6_SE_bb]+0x42): undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::PrintingPolicy const&) const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import clpy_setup_build
  File "/home/sakamoto/Source/clpy-release/clpy/clpy_setup_build.py", line 29, in <module>
    raise RuntimeError('Build ultima is failed.')
RuntimeError: Build ultima is failed.
```

使用している環境は
- Ubuntu 18.04 LTS
- CUDA 9.2
- LLVM Clang 6.0
    - LLVMとClangのみビルド。ほかのOptionalなものはビルドしてない

です。

どなたか何かご存知でしょうか？

**Comment by vorj** [comment]
Ultimaを書いた者です。

おそらくですが、LLVM Clangのビルド時にC++11 ABIを使わずにlibToolingをビルドしていて、Ultimaのビルド時にC++11 ABIを有効にしてビルドしてしまっているので、そこでlibToolingのいくつかのシンボルがリンクエラーになっている、というように見えます。  
少し手元で調査してみます。

**Comment by LWisteria** [comment]
https://github.com/fixstars/clpy#recommended-system にあるとおり、開発時には16.04を使っているので、その違いということはないでしょうか？
コンパイラその他のライブラリのバージョンが変わりましたし、そもそも18.04 LTSはまだ出たばかりなので安定性に疑問があります・・・。

**Comment by telmin** [comment]
コメントありがとうございます。16.04でも試してみます。

**Comment by vorj** [comment]
再現できました。やはりlibToolingがC++11 ABIを使わずにビルドされていることが問題で、CMakeを使ってLLVM Clangをビルドしている場合、 `cmake` コマンドのオプションに `-DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=1"` を追加してビルドすることで解決すると思います。

**Comment by vorj** [comment]
@telmin 念の為確認なのですが、エラーが発生した環境で使用していたGCCのバージョンを教えていただけますでしょうか

**Comment by telmin** [comment]
@vorj ご確認ありがとうございます。こちらでも上記オプションを付与してClangをビルド中です
gccのバージョンは以下になります。

```
~$ gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by vorj** [comment]
@telmin バージョン確認ありがとうございます。  
以下のbashスクリプトの実行結果を教えていただけますでしょうか。

```bash
cat << EOS > /tmp/abi_test.cpp
#include<string>
void test(std::string){}
EOS
g++ -std=c++11 -c -o /tmp/abi_test.o /tmp/abi_test.cpp
nm /tmp/abi_test.o | c++filt
```

**Comment by telmin** [comment]
遅くなってすいません。
貼っていただいたスクリプトの実行結果は以下のようになっています。
```
0000000000000000 T test(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
0000000000000000 r std::piecewise_construct
```

**Comment by vorj** [comment]
C++11 ABIはGCC 5以降(に付属のlibstdc++)で実装されており、ディストリビューションやユーザーが設定を変更しない限りデフォルトでC++11 ABIを使用するようになっています。  
また、Ubuntuは16.04/18.04共にその設定を変更していません。  
さらに、telminさんに実行していただいたスクリプトの結果から、お手元のGCCでもデフォルトでC++11 ABIが有効なようです。

LLVM/ClangがC++03 ABIでビルドされた状況ですが、考えられるのは以下の3つです。

1. C++11 ABIが存在しないGCC(4以前)でClangをビルドした
    - Ubuntuのパッケージで入れている場合はCMakeに `-DCMAKE_CXX_COMPILER=g++-4.9` を渡すなどする必要があります。
    - わざわざGCC 4以前をインストールされたりビルドオプションを指定されたり、ということは考えにくいです。
1. GCC 5以降を使って、Clangのビルド時にC++11 ABIを無効にして(`-D_GLIBCXX_USE_CXX11_ABI=0`)ビルドした
    - わざわざこの設定をされたとは考えにくいです。
1. デフォルトでC++11 ABIを無効にしたGCC 5以降を使ってClangをビルドした
    - GCC 4以前でビルドされたライブラリを常用する場合などに考えられる状況です。
    - 実行していただいたスクリプトの実行結果から、少なくともGCCに直接変更が加えられていたり、bash環境下でそういったaliasがはられたりはしていなさそうです。
        - 常用しているシェルがbashでない場合は一応 `g++` や `c++` のaliasと環境変数 `CXX` について確認してみてください。(多分無いと思いますが…)

以上から、申し訳ありませんがtelminさんの環境でLLVM/ClangがC++03 ABIでビルドされてしまった原因について見当はつきませんでした。  

ひとまず、 `-DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=1"` を付けてビルドしたClangでUltimaのビルドが通るかどうかを確認していただけますでしょうか。

**Comment by telmin** [comment]
詳細なご確認、ありがとうございます。
ちょっと手元の環境がぶっ壊れてしまったので、確認まで少しお時間ください…

確認できましたらまた書き込みます

**Comment by telmin** [comment]
@vorj 遅くなりました。すいません。

Ubuntu 16.04環境下でUltimaのビルドが通ることを確認できました。  
色々とご対応ありがとうございました。

**Comment by vorj** [comment]
@telmin ご報告ありがとうございます！ビルドが通ってよかったです。

ClangのABIを確認し、それに合わせてUltimaをビルドするよう #46 にて修正を行いました。
当該PRがマージされ次第このissueは閉じます。

**Comment by telmin** [comment]
@vorj #46 のご対応も、併せてありがとうございます！

**Comment by LWisteria** [comment]
@telmin thanks for reporting!

@vorj thank you PR

**Comment by vorj** [comment]
#46 がマージされたので閉じます。
