### ISSUE TITLE
Can not run ImageNet example

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#47]
Can not run ImageNet example due to runtime error at vega and titanv.
error at vega
```
error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR
```
error at titanv
```
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -9999
```

**Comment by ghost** [comment]
full error message at vega
https://github.com/fixstars/clpy/issues/41#issuecomment-414540617
full error message at titanv
https://github.com/fixstars/clpy/issues/41#issuecomment-414541583

**Comment by LWisteria** [comment]
@vorj @t-kitawaki please investigate this problem

**Comment by LWisteria** [comment]
@t-kitawaki do you confirm that this problem was fixed?

**Comment by ghost** [comment]
@LWisteria I got another error message...
titanv and vega output same error messages.
```
Exception in main training loop: Return code:-6
STDERR:
terminate called after throwing an instance of 'std::runtime_error'
  what():  only 'raw' CArray can subscript

Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 541, in update
    loss.backward()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/variable.py", line 889, in backward
    self._backward_main(retain_grad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/variable.py", line 990, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 514, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/pooling/max_pooling_2d.py", line 87, in backward
    return MaxPooling2DGrad(self).apply(gy)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/pooling/max_pooling_2d.py", line 169, in forward_gpu
    gx)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 158, in clpy.core.core.compile_with_cache
  File "clpy/core/carray.pxi", line 174, in clpy.core.core.compile_with_cache
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/clpy-2.1.0a0-py3.6-linux-x86_64.egg/clpy/__main__.py", line 8, in <module>
    exec(f.read())
  File "<string>", line 164, in <module>
  File "<string>", line 160, in main
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/optimizer.py", line 541, in update
    loss.backward()
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/variable.py", line 889, in backward
    self._backward_main(retain_grad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/variable.py", line 990, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 514, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/pooling/max_pooling_2d.py", line 87, in backward
    return MaxPooling2DGrad(self).apply(gy)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/function_node.py", line 337, in forward
    return self.forward_gpu(inputs)
  File "/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/functions/pooling/max_pooling_2d.py", line 169, in forward_gpu
    gx)
  File "clpy/core/elementwise.pxi", line 631, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/util.pyx", line 40, in clpy.util.memoize.decorator.ret
  File "clpy/core/elementwise.pxi", line 482, in clpy.core.core._get_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 16, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/elementwise.pxi", line 45, in clpy.core.core._get_simple_elementwise_kernel
  File "clpy/core/carray.pxi", line 158, in clpy.core.core.compile_with_cache
  File "clpy/core/carray.pxi", line 174, in clpy.core.core.compile_with_cache
clpy.backend.ultima.exceptions.UltimaRuntimeError: Return code:-6
STDERR:
terminate called after throwing an instance of 'std::runtime_error'
  what():  only 'raw' CArray can subscript
```

**Comment by vorj** [comment]
@LWisteria @t-kitawaki Sorry, it's my fault. I fixed the problem at #52, and I confirmed that ImageNet example starts to run.

**Comment by LWisteria** [comment]
@nsakabe-fixstars can you check this issue was solved?

**Comment by ghost** [comment]
I also confirmed starting training ImageNet with the #52 pull-req.

**Comment by LWisteria** [comment]
OK, thanks all!
