### ISSUE TITLE
Support huge size ndarray (more than max global work item size)

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#7]
Current clpy simply launch kernel with [global work item size = ndarray.size](https://github.com/fixstars/clpy/blob/dec25c342032617d61e6b71ad5836b16005cc29a/clpy/backend/function.pyx#L149).

However, global work item size is limited by [clGetDeviceInfo<CL_DEVICE_MAX_WORK_ITEM_SIZES>](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clGetDeviceInfo.html). Make loop in kernel or clEnqueueKernel in several times when ndarray.size is more than it.

**Comment by LWisteria** [comment]
@t-kitawaki take this please

**Comment by ghost** [comment]
I tried TestClpyElementwiseKernel.test_vectoradd with many elements in titanv.
Test with 2^29 (=536870912) elements for each vector was passed.
Test with 2^30 (=1073741824) elements for each vector was failed with `clpy.backend.opencl.exceptions.OpenCLRuntimeError: CL_MEM_OBJECT_ALLOCATION_FAILURE`.
Because requested memory size is 2^30 * 4byte(float32) * 3 = 12GB but titanv has only 11 GB video memory.

**Comment by LWisteria** [comment]
Create simple ElementwiseKernel which take only one argument instead of vectoradd.

**Comment by LWisteria** [comment]
And you don't need float32 for this test. int8_t is enough, right?

**Comment by ghost** [comment]
I create simple ElementwiseKernel which take only one argument and return that as it is.
And test it with int8 array.
Test with 2^31 (=2147483648) elements vector was passed.
Test with 2^32 (=4294967296) elements for each vector was failed with `clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -9999`

```
Error
Traceback (most recent call last):
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/kitawaki/.pyenv/versions/3.6.5/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/kitawaki/clpy-chainer/clpy/tests/clpy_tests/core_tests/test_elementwise.py", line 171, in test_bigvector
    y = kernel(x)
  File "clpy/core/elementwise.pxi", line 685, in clpy.core.core.ElementwiseKernel.__call__
  File "clpy/backend/function.pyx", line 165, in clpy.backend.function.Function.linear_launch
  File "clpy/backend/function.pyx", line 126, in clpy.backend.function._launch
  File "clpy/backend/opencl/utility.pyx", line 140, in clpy.backend.opencl.utility.RunNDRangeKernel
  File "clpy/backend/opencl/api.pyx", line 256, in clpy.backend.opencl.api.WaitForEvents
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -9999 



Ran 1 test in 0.838s

FAILED (errors=1)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "clpy/backend/opencl/env.pyx", line 74, in clpy.backend.opencl.env.release
  File "clpy/backend/opencl/api.pyx", line 235, in clpy.backend.opencl.api.Flush
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status
clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -9999 

Process finished with exit code 1
```

**Comment by ghost** [comment]
https://streamhpc.com/blog/2013-04-28/opencl-error-codes/
ERROR -9999 is
Errors thrown by Vendors

Code | Vendor | Function(s) | Description
-- | -- | -- | --
-9999 | NVidia | clEnqueueNDRangeKernel | Illegal read or write to a buffer

**Comment by ghost** [comment]
I checked titanv's clinfo.
Max work item sizes is 1024x1024x64

This issue try to fix error which happen when ndarray bigger max work item sizes is used.
But "OpenCLRuntimeError: UNKNOWN ERROR: -9999" which I found has different occurrence condition.

titanv's clinfo also shows 
Max memory allocation is 3162554368 (2.945GiB)
And that Error happen when I try to use 4294967296(4Gib).
That Errors reason is try to allocate large memory size bigger than max memory allocation size?

**Comment by LWisteria** [comment]
2^31 > 1024x1024x64=2^10 x 2^10 x 2^6 = 2^26. Therefore the error must be happened.

**Comment by LWisteria** [comment]
Can you check what happened when you execute global items more than CL_DEVICE_MAX_WORK_ITEM_SIZES **on pure OpenCL program written in C/C++**, without clpy?

**Comment by ghost** [comment]
OK. I'll try that.

**Comment by LWisteria** [comment]
And I suggest developing on the primary machine (AMD vega) instead of secondary (NVIDIA titanv) because NVIDIA does not implement OpenCL so well. (That's why we call vega primary and titanv secondary)

**Comment by ghost** [comment]
I create pure OpenCL program in c.
The program make huge char array, and invert sign of all elements in the array by using OpenCL, and check calculation results.
I run it at vega machine.

vega OpenCL information
```
Global memory size:                            16978542592
Max work items dimensions:                     3
  Max work items[0]:                           1024
  Max work items[1]:                           1024
  Max work items[2]:                           1024
```

Test with 2^30 (=1073741824) elements was passed.
Test with 2^30 *1.5 (=1610612736) elements was passed. 
Test with 2^31 (=2147483648) elements was passed.
Test with 2^31 + 1 (=2147483649) elements was failed.
Test with 2^31 *1.5 (=3221225472) elements was failed.
(suspended because of too long execution time.)

2^31 > 1024 * 1024 * 1024 = 2^30.
So I expect error at test with 2^31 elements, but the case was passed.

**Comment by ghost** [comment]
I run it at titanv machine.
titanv OpenCL information
```
Global memory size                              12650217472 (11.78GiB)
Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
```

Test with 2^30 (=1073741824) elements was passed.
Test with 2^30 *1.5 (=1610612736) elements was passed.
Test with 2^31 (=2147483648) elements was passed.
Test with 2^31 + 1 (=2147483649) elements was failed.
Test with 2^31 *1.5 (=3221225472) elements was failed. 
(result(that was all zero array) is not correct)

2^30 > 1024 * 1024 * 64 = 2^26.
So I expect error at test with 2^30 elements, but the case was passed.

**Comment by ghost** [comment]
I run it at furyx machine.
furyx OpenCL information
```
Global memory size:                            4272246784
Max work items dimensions:                     3
  Max work items[0]:                           1024
  Max work items[1]:                           1024
  Max work items[2]:                           1024

```

Test with 2^31 (=2147483648) elements was passed.

2^31 > 1024 * 1024 * 1024 = 2^30.
So I expect error at test with 2^31 elements, but the case was passed.

**Comment by ghost** [comment]
These test shows that, calculation with huge global size more than Max work item size will not cause explicit error.
And, problem will not happen while 2^31 *1.5 elements calculation.
But, 2^31 *1.5 elements calculation (and maybe also more than 2^31 *1.5 elements) will cause incorrect result or too long execution time which is not scaled.

**Comment by ghost** [comment]
test codes 
```c
//main.cpp
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#ifdef __APPLE__
#include <OpenCL/opencl.h>
#else
#include <CL/cl.h>
#endif

#define MAX_SOURCE_SIZE (0x100000)
#define CALC_SIZE (2147483648)

int main()
{
    cl_platform_id platform_id = NULL;
    cl_device_id device_id = NULL;
    cl_context context = NULL;
    cl_command_queue command_queue = NULL;
    cl_mem Amobj = NULL;
    cl_mem Bmobj = NULL;
    cl_program program = NULL;
    cl_kernel kernel = NULL;
    cl_uint ret_num_devices;
    cl_uint ret_num_platforms;
    cl_int ret;

    size_t max_work_item_dimensions;
    size_t *max_work_item_sizes;

    long int i;
    char *A;
    char *B;

    printf("make array (test size is %ld)\n", CALC_SIZE );
    fflush(stdout);
    A = (char *)malloc(CALC_SIZE*sizeof(char));
    B = (char *)malloc(CALC_SIZE*sizeof(char));

    /* データを初期化 */
    srand((unsigned)time(NULL));
    for (i=0; i<CALC_SIZE; i++) {
            A[i] = rand()%128;
    }

    printf("check opencl info\n");
    fflush(stdout);

    FILE *fp;
    const char fileName[] = "./test.cl";
    size_t source_size;
    char *source_str;

    /* カーネルを含むソースコードをロード */
    fp = fopen(fileName, "r");
    if (!fp) {
        fprintf(stderr, "Failed to load kernel.\n");
        exit(1);
    }
    source_str = (char *)malloc(MAX_SOURCE_SIZE);
    source_size = fread( source_str, 1, MAX_SOURCE_SIZE, fp );
    fclose( fp );


    /* プラットフォーム・デバイスの情報の取得 */
    ret = clGetPlatformIDs(1, &platform_id, &ret_num_platforms);
    ret = clGetDeviceIDs( platform_id, CL_DEVICE_TYPE_DEFAULT, 1, &device_id, &ret_num_devices);

    ret = clGetDeviceInfo( device_id, CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS, sizeof(max_work_item_dimensions), &max_work_item_dimensions, NULL);
    printf("CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS = %d\n", (int)max_work_item_dimensions);
    max_work_item_sizes = (size_t *)calloc(max_work_item_dimensions, sizeof(size_t));
    ret = clGetDeviceInfo( device_id, CL_DEVICE_MAX_WORK_ITEM_SIZES, max_work_item_dimensions* sizeof(size_t), max_work_item_sizes, NULL);
    printf("CL_DEVICE_MAX_WORK_ITEM_SIZES = (");
    for (i=0; i<max_work_item_dimensions; i++){
        printf("%d,",(int)max_work_item_sizes[i]);
    }
    printf(")\n");

    printf("run test\n" );
    fflush(stdout);

    /* OpenCLコンテキストの作成 */
    context = clCreateContext( NULL, 1, &device_id, NULL, NULL, &ret);

    /* コマンドキューの作成 */
    command_queue = clCreateCommandQueue(context, device_id, 0, &ret);

    /* バッファオブジェクトの作成 */
    Amobj = clCreateBuffer(context, CL_MEM_READ_WRITE, CALC_SIZE*sizeof(char), NULL, &ret);
    Bmobj = clCreateBuffer(context, CL_MEM_READ_WRITE, CALC_SIZE*sizeof(char), NULL, &ret);

    /* メモリバッファにデータを転送 */
    ret = clEnqueueWriteBuffer(command_queue, Amobj, CL_TRUE, 0, CALC_SIZE*sizeof(char), A, 0, NULL, NULL);

    /* 読み込んだソースからカーネルプログラムを作成 */
    program = clCreateProgramWithSource(context, 1, (const char **)&source_str, (const size_t *)&source_size, &ret);
    ret     = clBuildProgram(program, 1, &device_id, NULL, NULL, NULL);

    /* データ並列のOpenCLカーネルの作成 */
    kernel = clCreateKernel(program, "dataParallel", &ret);

    /* OpenCLカーネル引数の設定 */
    ret = clSetKernelArg(kernel, 0, sizeof(cl_mem), (void *)&Amobj);
    ret = clSetKernelArg(kernel, 1, sizeof(cl_mem), (void *)&Bmobj);

    size_t global_item_size = CALC_SIZE;
    size_t local_item_size = 1;

    /* OpenCLカーネルをデータ並列で実行 */
    ret = clEnqueueNDRangeKernel(command_queue, kernel, 1, NULL,
                                 &global_item_size, &local_item_size, 0, NULL, NULL);

    /* メモリバッファから結果を取得 */
    ret = clEnqueueReadBuffer(command_queue, Bmobj, CL_TRUE, 0, CALC_SIZE*sizeof(char), B, 0, NULL, NULL);

    printf("test has end\n");
    fflush(stdout);

    long int error_count = 0;
    for (i=0; i<CALC_SIZE; i++) {
        if(A[i] != - B[i]){
            error_count++;
        }
    }

    printf("error : %d\n", error_count);
    fflush(stdout);

    /* 終了処理 */
    ret = clFlush(command_queue);
    ret = clFinish(command_queue);
    ret = clReleaseKernel(kernel);
    ret = clReleaseProgram(program);
    ret = clReleaseMemObject(Amobj);
    ret = clReleaseMemObject(Bmobj);
    ret = clReleaseCommandQueue(command_queue);
    ret = clReleaseContext(context);

    free(source_str);

    free(A);
    free(B);

    return 0;
}
```
```c
//test.cl
__kernel void dataParallel(__global char* A, __global char* B)
{
    int i = get_global_id(0);

    B[i] = - A[i];
}
```

**Comment by ghost** [comment]
These investigation show that one dimension huge array bigger than 2^31(=2147483648) calculation by openCL in primary and secondary  machine will fail.
(I think threshold whether fail test will be different number depends on GPU. In this case that was same.)
And fail condition is different.
Primary machine (vega) is stopped (and need manual suspend) and secondary machine (titanv) return incorrect result.
Both pattern didn't show any useful error that I wanted to get.

**Comment by ghost** [comment]
I try to reproduce them in clpy ElementwiseKernel.
In primary machine I can not reproduce them due to MemoryError.
(because primary machine has only 8GB main memory)
In secondary machine I can reproduce them.
(Error happen with same size of array)

**Comment by ghost** [comment]
@LWisteria 
I think, I (or we?) had misunderstanding for limitation of openCL work item size.
Both CL_DEVICE_MAX_WORK_ITEM_SIZES and CL_DEVICE_MAX_WORK_GROUP_SIZE is limitation for work-items in a work-group (local work item size).
And global work item size has no limitation generally.
That's why I can not find error when global work item size exceeds CL_DEVICE_MAX_WORK_ITEM_SIZES and CL_DEVICE_MAX_WORK_GROUP_SIZE.
https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html
https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clGetDeviceInfo.html

If these understanding is correct, this issue is not necessary.
(Because clpy use None or vector which all elements is 1 as local work item size.)
But calculation with huge array (longer than 2^31) have some problem.
This problem is caused by another reason (I think memory size is suspicious).
Do we have to solve this problem?

Please check global work item size limitation.
And decide to close or change this issue (or point out a mistake if my comment is wrong).

**Comment by ghost** [comment]
For our reference, I search huge array calculation in CUPY.
CUPY can not calculate huge array too (but limitation size was different)

I try this code
```python
import numpy as np
import cupy as cp

if __name__ == '__main__':
    n = 2 ** 33
    # x_np = np.ones((n,), dtype="int8")

    x_cp = cp.ones((n,), dtype="int8")

    kernel = cp.ElementwiseKernel(
        'T x',
        'T y',
        '''
            y = -x;
        ''',
        'vector')
    y_cp = kernel(x_cp)

    actual = y_cp.get()
    # expected = - x_np
    # print(np.allclose(actual, expected))
```
and get memory error
```
Traceback (most recent call last):
  File "/home/kitawaki/cupy-test/test.py", line 17, in <module>
    y_cp = kernel(x_cp)
  File "cupy/core/elementwise.pxi", line 515, in cupy.core.core.ElementwiseKernel.__call__
  File "cupy/core/elementwise.pxi", line 340, in cupy.core.core._get_out_args_with_params
  File "cupy/core/core.pyx", line 120, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 483, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1030, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1051, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 865, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 886, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 660, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 8589934592 bytes (total 17179869184 bytes)

Process finished with exit code 1
```

**Comment by ghost** [comment]
I test less memory usage and huge global work item size (2^35) openCL program.
And I confirmed that openCL can run huge global work item program, unless try to using too many memory. 

test code
```main.cpp
// main.cpp
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#ifdef __APPLE__
#include <OpenCL/opencl.h>
#else
#include <CL/cl.h>
#endif

#define MAX_SOURCE_SIZE (0x100000)
#define CALC_SIZE (1UL<<35)

int main()
{
    cl_platform_id platform_id = NULL;
    cl_device_id device_id = NULL;
    cl_context context = NULL;
    cl_command_queue command_queue = NULL;
    cl_mem Amobj = NULL;
    cl_program program = NULL;
    cl_kernel kernel = NULL;
    cl_uint ret_num_devices;
    cl_uint ret_num_platforms;
    cl_int ret;

    size_t max_work_item_dimensions;
    size_t *max_work_item_sizes;

    long int i;
    unsigned long *A;

    printf("make array (test size is %ld)\n", CALC_SIZE );
    fflush(stdout);
    A = (unsigned long *)malloc(sizeof(unsigned long));

    /* データを初期化 */
    A[i] = 0;

    printf("check opencl info\n");
    fflush(stdout);

    FILE *fp;
    const char fileName[] = "./test.cl";
    size_t source_size;
    char *source_str;

    /* カーネルを含むソースコードをロード */
    fp = fopen(fileName, "r");
    if (!fp) {
        fprintf(stderr, "Failed to load kernel.\n");
        exit(1);
    }
    source_str = (char *)malloc(MAX_SOURCE_SIZE);
    source_size = fread( source_str, 1, MAX_SOURCE_SIZE, fp );
    fclose( fp );


    /* プラットフォーム・デバイスの情報の取得 */
    ret = clGetPlatformIDs(1, &platform_id, &ret_num_platforms);
    ret = clGetDeviceIDs( platform_id, CL_DEVICE_TYPE_DEFAULT, 1, &device_id, &ret_num_devices);

    ret = clGetDeviceInfo( device_id, CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS, sizeof(max_work_item_dimensions), &max_work_item_dimensions, NULL);
    printf("CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS = %d\n", (int)max_work_item_dimensions);
    max_work_item_sizes = (size_t *)calloc(max_work_item_dimensions, sizeof(size_t));
    ret = clGetDeviceInfo( device_id, CL_DEVICE_MAX_WORK_ITEM_SIZES, max_work_item_dimensions* sizeof(size_t), max_work_item_sizes, NULL);
    printf("CL_DEVICE_MAX_WORK_ITEM_SIZES = (");
    for (i=0; i<max_work_item_dimensions; i++){
        printf("%d,",(int)max_work_item_sizes[i]);
    }
    printf(")\n");

    printf("run test\n" );
    fflush(stdout);

    /* OpenCLコンテキストの作成 */
    context = clCreateContext( NULL, 1, &device_id, NULL, NULL, &ret);

    /* コマンドキューの作成 */
    command_queue = clCreateCommandQueue(context, device_id, 0, &ret);

    /* バッファオブジェクトの作成 */
    Amobj = clCreateBuffer(context, CL_MEM_READ_WRITE, sizeof(unsigned long), NULL, &ret);
    printf("clCreateBuffer:%d\n",(int)ret);

    /* メモリバッファにデータを転送 */
    ret = clEnqueueWriteBuffer(command_queue, Amobj, CL_TRUE, 0, sizeof(unsigned long), A, 0, NULL, NULL);
       printf("clEnqueueWriteBuffer:%d\n",(int)ret);

    /* 読み込んだソースからカーネルプログラムを作成 */
    program = clCreateProgramWithSource(context, 1, (const char **)&source_str, (const size_t *)&source_size, &ret);
    ret     = clBuildProgram(program, 1, &device_id, NULL, NULL, NULL);
    printf("clBuildProgram:%d\n",(int)ret);

    /* データ並列のOpenCLカーネルの作成 */
    kernel = clCreateKernel(program, "dataParallel", &ret);

    /* OpenCLカーネル引数の設定 */
    ret = clSetKernelArg(kernel, 0, sizeof(cl_mem), (void *)&Amobj);
    printf("clSetKernelArg:%d\n",(int)ret);

    size_t global_item_size = CALC_SIZE;
    size_t local_item_size = 1;

    /* OpenCLカーネルをデータ並列で実行 */
    ret = clEnqueueNDRangeKernel(command_queue, kernel, 1, NULL,
                                 &global_item_size, &local_item_size, 0, NULL, NULL);
    printf("clEnqueueNDRangeKernel:%d\n",(int)ret);

    /* メモリバッファから結果を取得 */
    ret = clEnqueueReadBuffer(command_queue, Amobj, CL_TRUE, 0, sizeof(unsigned long), A, 0, NULL, NULL);
    printf("clEnqueueReadBuffer:%d\n",(int)ret);

    printf("test has end\n");
    fflush(stdout);

    
    printf("result: %ld (%ld)\n", A[0],CALC_SIZE);
    fflush(stdout);

    /* 終了処理 */
    ret = clFlush(command_queue);
    ret = clFinish(command_queue);
    ret = clReleaseKernel(kernel);
    ret = clReleaseProgram(program);
    ret = clReleaseMemObject(Amobj);
    ret = clReleaseCommandQueue(command_queue);
    ret = clReleaseContext(context);
    
    free(source_str);

    free(A);

    return 0;
}
```

```test.cl
// test.cl
#pragma OPENCL EXTENSION cl_khr_int64_base_atomics : enable
__kernel void dataParallel(__global unsigned long *A)
{
    atom_add(A, 1UL);
}
```

**Comment by LWisteria** [comment]
We do not have to modify something for this issue. Thanks for investigation!
